/*
Generated by Yara-Rules
On 18-11-2021
*/
include "./antidebug_antivm/antidebug_antivm.yar"
include "./capabilities/capabilities.yar"
include "./crypto/crypto_signatures.yar"
include "./maldocs/Maldoc_PowerPointMouse.yar"
include "./maldocs/maldoc_somerules.yar"
include "./maldocs/Maldoc_HWP.yar"
include "./malware/APT_DPRK_ROKRAT.yar"
include "./malware/MALW_Magento_backend.yar"
include "./malware/MALW_Miscelanea.yar"
include "./malware/RANSOM_MS17-010_Wannacrypt.yar"
include "./malware/RAT_Ratdecoders.yar"
include "./packers/packer.yar"
include "./packers/packer_compiler_signatures.yar"
include "./packers/peid.yar"
